#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
version: 0.0.0.{build}
install:
  - ps: Update-AppveyorBuild -Version $(version)

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(version)
  assembly_file_version: $(version)
  assembly_informational_version: $(version)
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

build:
  project: Source\SharpVectors.sln

after_build:
  - ps: nuget pack "Source\SharpVectorsReloaded.nuspec" -Properties "version=0.0.0.0"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: <your secret here>
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
