#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

# we forked from the 1.7.1 release, so all of our builds will be 1.7.1.x
# note that this is shorthand for APPVEYOR_BUILD_VERSION
version: 1.7.1.{build}

pull_requests:
  do_not_increment_build_number: true

# foreach sdk-style project, update the version fields to 1.7.1.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
 # foreach assemblyinfo, update the version fields to 1.7.1.{build} 
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - ps: nuget restore .\Source\SharpVectors.sln

build:
  project: .\Source\SharpVectors.sln

# this project uses nuget pack instead of relying on msbuild packing.
# it's possible to set up your build step to produce packages.
after_build:
  - ps: nuget pack ".\Source\SharpVectors.nuspec" -Properties "version=$env:APPVEYOR_BUILD_VERSION"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

# take the nupkg from the root directory and add it to the appveyor artifacts for this build
# in the case of this project, they also store old packages in the nuget\ folder, so we only match
# on packages in the root directory
artifacts:
  - path: '.\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# this deploys all of the artifacts packaged in the previous step to nuget if the build is happening on master
# the api key is encrypted.
# this deployment section is not at all customized for this particular repository.
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: I2fPs5m1kSHTtbHd03Lu+cM8KGP97xPnopLZ6OVhoLMRWfVy/cEcVp0BKYB3bf3gT/Zp1qp3tRfFfpAvwy6jNcmY6pI3Y1fWoKd6BVyutj1kz+3BQVkbU3CKTh5VyyvO6OZBS/MSlqSs8c7SVaqZwiMaDOUwAKU23gKjnGKpKCc=
  skip_symbols: true
  on:
    branch: master