#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
version: 0.0.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

  before_build:
    - ps: nuget restore .\Source\SharpVectors.sln

build:
  project: .\Source\SharpVectors.sln

after_build:
  - ps: nuget pack ".\Source\SharpVectorsReloaded.nuspec" -Properties "version=0.0.0.0"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: <your secret here>
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
