#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
version: 1.7.1.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - ps: nuget restore .\Source\SharpVectors.sln

build:
  project: .\Source\SharpVectors.sln

after_build:
  - ps: nuget pack ".\Source\SharpVectors.nuspec" -Properties "version=$env:APPVEYOR_BUILD_VERSION"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '.\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
- provider: NuGet
  server: https://artifactory.articulate.com/artifactory/api/nuget/nuget-local
  api_key:
    secure: I2fPs5m1kSHTtbHd03Lu+cM8KGP97xPnopLZ6OVhoLMRWfVy/cEcVp0BKYB3bf3gT/Zp1qp3tRfFfpAvwy6jNcmY6pI3Y1fWoKd6BVyutj1kz+3BQVkbU3CKTh5VyyvO6OZBS/MSlqSs8c7SVaqZwiMaDOUwAKU23gKjnGKpKCc=
  skip_symbols: true
  artifact: PackageFile
  on:
    branch: master